[[packages]]
name = "STM32"
releases = [
]

[[packages]]
name = "pikaStdLib"
releases = [
  "v1.0.1 c4f0d45aec94e155998c110fbfb64f17c54f7766",
]

[[packages]]
name = "pikaStdDevice"
releases = [
  "v1.3.0 c4f0d45aec94e155998c110fbfb64f17c54f7766",
]

[[packages]]
name = "pikascript-core"
releases = [
  "v0.8.1 c4f0d45aec94e155998c110fbfb64f17c54f7766",
]
